<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRUSVfYM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRUSVfYM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRUSVfYM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRUSVfYM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRUSVfYM\App_KernelDevDebugContainer([
    'container.build_hash' => 'RUSVfYM',
    'container.build_id' => '117ee8ed',
    'container.build_time' => 1711453206,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRUSVfYM');
