<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5t3xnqq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5t3xnqq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5t3xnqq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5t3xnqq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5t3xnqq\App_KernelDevDebugContainer([
    'container.build_hash' => '5t3xnqq',
    'container.build_id' => 'e048f403',
    'container.build_time' => 1713776126,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5t3xnqq');
