<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaoQVkz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaoQVkz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIaoQVkz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIaoQVkz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIaoQVkz\App_KernelDevDebugContainer([
    'container.build_hash' => 'IaoQVkz',
    'container.build_id' => '89a8a596',
    'container.build_time' => 1711451021,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaoQVkz');
